packages:
  - packages/*
  - internals/*
  - stories/*
  - packages/nuxt/playground

ignoredBuiltDependencies:
  - puppeteer

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - msw
  - vue-demi
