shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar

autoInstallPeers: false

packages:
  - docs
  - packages/*
  - internals/*
  - stories/*
  - packages/nuxt/playground

ignoredBuiltDependencies:
  - '@aa900031/eslint-config'

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - msw
  - sharp
  - vue-demi
  - better-sqlite3
