ignoreWorkspaceRootCheck: true
shamefullyHoist: true
shellEmulator: true
strictPeerDependencies: false
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 43200
autoInstallPeers: false

packages:
  - docs
  - packages/*
  - internals/*
  - stories/*
  - packages/nuxt/playground

overrides:
  '@tanstack/vue-query>vue-demi': latest

ignoredBuiltDependencies:
  - '@aa900031/eslint-config'

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - msw
  - sharp
  - vue-demi
  - better-sqlite3
