ignoreWorkspaceRootCheck: true
shamefullyHoist: true
shellEmulator: true
strictPeerDependencies: false
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 43200
autoInstallPeers: false

packages:
  - docs
  - examples/*
  - packages/*
  - internals/*
  - stories/*
  - packages/nuxt/playground

overrides:
  '@tanstack/vue-query>vue-demi': latest

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  msw: true
  sharp: true
  vue-demi: true
  better-sqlite3: true
  '@aa900031/eslint-config': false
